#/bin/sh
wget https://cni.iisc.ac.in/wp-content/uploads/2020/10/Evolution-of-a-Population-of-Selfish-Agents-on-a-Network.pdf
wget https://cni.iisc.ac.in/wp-content/uploads/2020/10/Large-deviations-of-mean-field-interacting-particle-systems-in-a-fast-varying-environment.pdf
wget https://cni.iisc.ac.in/wp-content/uploads/2020/10/Large-Time-Behaviour-and-the-Second-Eigenvalue-Problem-for-Finite-State-Mean-Field-Interacting-Particle-Systems.pdf
wget https://cni.iisc.ac.in/wp-content/uploads/2020/07/Minimizing-Latency-for-Secure-Coded-Computing........pdf
wget https://cni.iisc.ac.in/wp-content/uploads/2020/07/Negative-Sampling-for-Hyperlink-Prediction-in-Networks.pdf
wget https://cni.iisc.ac.in/wp-content/uploads/2020/07/On-the-Latency-in-Vehicular-Control-using-Video-Streaming-over-Wi-Fi.pdf
wget https://cni.iisc.ac.in/wp-content/uploads/2020/08/Optimal-Pricing-in-Finite-Server-Systems.pdf
wget https://cni.iisc.ac.in/wp-content/uploads/2020/08/Optimal-Server-Selection-for-Straggler-Mitigation.pdf
wget https://cni.iisc.ac.in/wp-content/uploads/2020/08/Probabilistic-Forwarding-of-Coded-Packets-on-Networks.pdf
wget https://cni.iisc.ac.in/wp-content/uploads/2020/08/Real-Time-Status-Updates-with-Perfect-Feedback.pdf
wget https://cni.iisc.ac.in/wp-content/uploads/2020/08/Tracking-an-Auto-Regressive-Process-with-Limited-Communication-per-Unit-Time.pdf
wget https://cni.iisc.ac.in/wp-content/uploads/2020/10/Tracking-an-Auto-Regressive-Process-with-Limited-Communication-per-Unit-Time.pdf
wget https://cni.iisc.ac.in/wp-content/uploads/2020/08/Probabilistic-Forwarding-of-Coded-Packets-on-Networks-Conference.pdf
wget https://cni.iisc.ac.in/wp-content/uploads/2020/08/The-Effect-of-Introducing-Redundancy-in-a-Probabilistic-Forwarding-Protocol.pdf
wget https://cni.iisc.ac.in/wp-content/uploads/2021/02/Attention-Actor-Critic-algorithm-for-Multi-Agent-Constrained-Co-operative-Reinforcement-Learning-3.pdf
wget https://cni.iisc.ac.in/wp-content/uploads/2020/07/A-Convergent-Off-Policy-Temporal-Difference-Algorithm.pdf
wget https://cni.iisc.ac.in/wp-content/uploads/2020/10/A-Stochastic-Game-Framework-for-Efficient-Energy-Management-in-Microgrid-Networks-2.pdf
wget https://cni.iisc.ac.in/wp-content/uploads/2020/02/Adaptive-Distributed-Stochastic-Gradient-Descent-for-Minimizing-delay-in-the-presence-of-Stragglers.pdf
wget https://cni.iisc.ac.in/wp-content/uploads/2020/10/C3MM-Clique-Closure-based-Hyperlink-Prediction.pdf
wget https://cni.iisc.ac.in/wp-content/uploads/2020/10/City-Scale-Agent-Based-Simulators-for-the-study-of-Non-Pharmaceutical-Interventions-in-the-Context-of-the-COVID-19-Epidemic.pdf
wget https://cni.iisc.ac.in/wp-content/uploads/2020/08/Coverage-Estimation-in-Outdoor-Heterogeneous-Propagation-Environments-1.pdf
